### PR TITLE
Return 503 status codes for exceptions and ignore exceptions on certain status codes

### PR DESCRIPTION
**Pull request by mt3593**

### CODE REVIEW

**Comment by joelittlejohn** [comment]
Couple of comments on this:
1. I think we need to find a better name for `:hystrix/do-not-trigger-on-status-codes`
2. I think we should have a sensible default. Maybe rather than restricting this to states codes we should allow a predicate to be specified here instead? That way the default behaviour could be _'status code >= 400 and < 500 (client errors) is a hystrix bad request'_

**Comment by joelittlejohn** [comment]
Oh also Mark, I think you need to add your mixrad.io email address into your github.com list of emails. Github will then know that it's you (you've got three different email addresses in this patch :smile:).

**Comment by mt3593** [comment]
I agree the name is awful, I spent a long time thinking about a good name but had to just use something in the mean time. I like the idea of the predicate rather than status codes, when I was thinking about the status codes I did wonder what codes you would actually use this for! only 404 came to mind. Making it a predicate will open up other options, good shout i'll have a look at changing that.
So what about :hystrix/ignore-predicate ?
Updated my github stuff. Think its my local setting that are out of whack, forgot to update them, thanks for letting me know :).

**Comment by joelittlejohn** [comment]
It would be good to keep this close to the existing Hystrix terminology.

I suggest :hystrix/bad-request-pred. This function is given the response,
and when it returns true, the failure is considered a bad request instead
of a downstream problem. Default should be (constantly false) I think.

**Pull request merged**
